# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defect-detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1052)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 1851, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.btnLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.btnLayout.setContentsMargins(0, 0, 0, 0)
        self.btnLayout.setObjectName("btnLayout")
        self.selectFolderBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.selectFolderBtn.setFont(font)
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.btnLayout.addWidget(self.selectFolderBtn)
        self.detectDefectsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.detectDefectsBtn.setFont(font)
        self.detectDefectsBtn.setObjectName("detectDefectsBtn")
        self.btnLayout.addWidget(self.detectDefectsBtn)
        self.segmentBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.segmentBtn.setFont(font)
        self.segmentBtn.setObjectName("segmentBtn")
        self.btnLayout.addWidget(self.segmentBtn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 180, 1851, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.imgLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.imgLayout.setContentsMargins(0, 0, 0, 0)
        self.imgLayout.setObjectName("imgLayout")
        self.originalImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.originalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImage.setObjectName("originalImage")
        self.imgLayout.addWidget(self.originalImage)
        self.detectImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.detectImage.setAlignment(QtCore.Qt.AlignCenter)
        self.detectImage.setObjectName("detectImage")
        self.imgLayout.addWidget(self.detectImage)
        self.segmentImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.segmentImage.setAlignment(QtCore.Qt.AlignCenter)
        self.segmentImage.setObjectName("segmentImage")
        self.imgLayout.addWidget(self.segmentImage)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 650, 271, 81))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectFolderBtn.setText(_translate("Form", "Select Image Folder"))
        self.detectDefectsBtn.setText(_translate("Form", "Detect Defects"))
        self.segmentBtn.setText(_translate("Form", "Segment"))
        self.originalImage.setText(_translate("Form", "Original Image"))
        self.detectImage.setText(_translate("Form", "Detect Image"))
        self.segmentImage.setText(_translate("Form", "Segment Image"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:64pt;\">Result</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
