# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defect-detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtGui import QPixmap, QImage

import cv2
import os
import time

class Ui_Form(object):
    
    
    def __init__(self):
        self.folderPath = ''
    
    
    def selectFolder(self):
        ''' Select Image of Folder '''
        
        # Open File Dialog
        folderPath = QFileDialog.getExistingDirectory(None, 'Select a folder:', './', QFileDialog.ShowDirsOnly)
        
        # Count Images number in folder
        numOfImages = len([name for name in os.listdir(folderPath) if os.path.isfile(os.path.join(folderPath, name))])
        
        if folderPath:
            self.folderImageNum.setText(f'{ numOfImages }')
            
        self.folderPath = folderPath
    
    
    def displayOriginalImage(self, image_path:str):
        ''' Display Image '''
        
        # Read Image
        pixmap = QPixmap(image_path)
        resized_pixmap = pixmap.scaled(self.originalImage.height(), self.originalImage.width(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.FastTransformation)
        self.originalImage.setPixmap(resized_pixmap)
        
        

    def detectDefects(self):
        
        # Get Folder Path
        
        if self.folderPath == '':
            reply = QMessageBox.information(None, 'Warning', 'Please select a folder first', QMessageBox.Ok)
            
            # if user click ok, then return to the main window
            if reply == QMessageBox.Ok:
                return None
        
        self.groundTruthTypeText.setText(self.folderPath)
        
        for index, filename in enumerate(os.listdir(self.folderPath)):
            
            
            self.image_path = os.path.join(self.folderPath, filename)
            self.displayOriginalImage(self.image_path)
            
            # display current image number
            self.currentImgNum.setText(f'{ index + 1 }')

            
            # display current image class
            if 'powder' in filename:
                self.groundTruthTypeText.setText((filename.split('_')[0] +  '_' + filename.split('_')[1]))
            else:
                self.groundTruthTypeText.setText(filename.split('_')[0])
                
    
    def segmentDefects(self):
        
        # Get Folder Path
        
        if self.folderPath == '':
            reply = QMessageBox.information(None, 'Warning', 'Please select a folder first', QMessageBox.Ok)
            
            # if user click ok, then return to the main window
            if reply == QMessageBox.Ok:
                return None
        
        self.groundTruthTypeText.setText(self.folderPath)
        
    
        
        
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1143, 721)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        Form.setFont(font)
        
        ### Btn Group
        
        # Select Folder Button
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1111, 71))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.btnLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.btnLayout.setContentsMargins(0, 0, 0, 0)
        self.btnLayout.setObjectName("btnLayout")
        self.selectFolderBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(20)
        self.selectFolderBtn.setFont(font)
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.btnLayout.addWidget(self.selectFolderBtn)
        # Click to batch select images from a folder
        self.selectFolderBtn.clicked.connect(self.selectFolder)
        ##############################
        
        # Detect Defects Button
        self.detectDefectsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(20)
        self.detectDefectsBtn.setFont(font)
        self.detectDefectsBtn.setObjectName("detectDefectsBtn")
        self.btnLayout.addWidget(self.detectDefectsBtn)
        # when i click this button, i want to run the detect function
        self.detectDefectsBtn.clicked.connect(self.detectDefects)
        
        ##############################
        self.segmentBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(20)
        self.segmentBtn.setFont(font)
        self.segmentBtn.setObjectName("segmentBtn")
        self.btnLayout.addWidget(self.segmentBtn)
        # when i click this button, i want to run the segment function
        self.segmentBtn.clicked.connect(self.segmentDefects)
        
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 1111, 331))
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.imgLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.imgLayout.setContentsMargins(0, 0, 0, 0)
        self.imgLayout.setObjectName("imgLayout")
        self.originalImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        self.originalImage.setFont(font)
        self.originalImage.setFrameShape(QtWidgets.QFrame.Box)
        self.originalImage.setText("")
        self.originalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImage.setObjectName("originalImage")
        self.imgLayout.addWidget(self.originalImage)
        self.detectImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        self.detectImage.setFont(font)
        self.detectImage.setFrameShape(QtWidgets.QFrame.Box)
        self.detectImage.setText("")
        self.detectImage.setAlignment(QtCore.Qt.AlignCenter)
        self.detectImage.setObjectName("detectImage")
        self.imgLayout.addWidget(self.detectImage)
        self.segmentImage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        self.segmentImage.setFont(font)
        self.segmentImage.setFrameShape(QtWidgets.QFrame.Box)
        self.segmentImage.setText("")
        self.segmentImage.setAlignment(QtCore.Qt.AlignCenter)
        self.segmentImage.setObjectName("segmentImage")
        self.imgLayout.addWidget(self.segmentImage)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(760, 490, 261, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.dcLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.dcLayout.setContentsMargins(0, 0, 0, 0)
        self.dcLayout.setObjectName("dcLayout")
        self.diceCoefficientText = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.diceCoefficientText.setFont(font)
        self.diceCoefficientText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.diceCoefficientText.setObjectName("diceCoefficientText")
        self.dcLayout.addWidget(self.diceCoefficientText)
        self.scoreOfDC = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.scoreOfDC.setFont(font)
        self.scoreOfDC.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scoreOfDC.setObjectName("scoreOfDC")
        self.dcLayout.addWidget(self.scoreOfDC)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 110, 1111, 26))
        self.widget.setObjectName("widget")
        self.imgTextLayout = QtWidgets.QHBoxLayout(self.widget)
        self.imgTextLayout.setContentsMargins(0, 0, 0, 0)
        self.imgTextLayout.setObjectName("imgTextLayout")
        self.originalImageText = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.originalImageText.setFont(font)
        self.originalImageText.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImageText.setObjectName("originalImageText")
        self.imgTextLayout.addWidget(self.originalImageText)
        self.detectImageText_ = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.detectImageText_.setFont(font)
        self.detectImageText_.setAlignment(QtCore.Qt.AlignCenter)
        self.detectImageText_.setObjectName("detectImageText_")
        self.imgTextLayout.addWidget(self.detectImageText_)
        self.segmentImageText = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.segmentImageText.setFont(font)
        self.segmentImageText.setAlignment(QtCore.Qt.AlignCenter)
        self.segmentImageText.setObjectName("segmentImageText")
        self.imgTextLayout.addWidget(self.segmentImageText)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 490, 331, 211))
        self.widget1.setObjectName("widget1")
        self.imgInfoLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.imgInfoLayout.setContentsMargins(0, 0, 0, 0)
        self.imgInfoLayout.setObjectName("imgInfoLayout")
        self.currentImgLayout = QtWidgets.QHBoxLayout()
        self.currentImgLayout.setContentsMargins(-1, -1, 90, -1)
        self.currentImgLayout.setObjectName("currentImgLayout")
        self.currentImageNumberText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.currentImageNumberText.setFont(font)
        self.currentImageNumberText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.currentImageNumberText.setObjectName("currentImageNumber")
        self.currentImgLayout.addWidget(self.currentImageNumberText)
        self.currentImgNum = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.currentImgNum.setFont(font)
        self.currentImgNum.setAlignment(QtCore.Qt.AlignCenter)
        self.currentImgNum.setObjectName("currentImgNum")
        self.currentImgLayout.addWidget(self.currentImgNum)
        self.signOfIsolation = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.signOfIsolation.setFont(font)
        self.signOfIsolation.setAlignment(QtCore.Qt.AlignCenter)
        self.signOfIsolation.setObjectName("signOfIsolation")
        self.currentImgLayout.addWidget(self.signOfIsolation)
        self.folderImageNum = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.folderImageNum.setFont(font)
        self.folderImageNum.setAlignment(QtCore.Qt.AlignCenter)
        self.folderImageNum.setObjectName("folderImageNum")
        self.currentImgLayout.addWidget(self.folderImageNum)
        self.imgInfoLayout.addLayout(self.currentImgLayout)
        self.gtLayout = QtWidgets.QHBoxLayout()
        self.gtLayout.setObjectName("gtLayout")
        self.typeText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.typeText.setFont(font)
        self.typeText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.typeText.setObjectName("typeText")
        self.gtLayout.addWidget(self.typeText)
        self.groundTruthTypeText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.groundTruthTypeText.setFont(font)
        self.groundTruthTypeText.setAlignment(QtCore.Qt.AlignCenter)
        self.groundTruthTypeText.setObjectName("groundTruthTypeText")
        self.gtLayout.addWidget(self.groundTruthTypeText)
        self.imgInfoLayout.addLayout(self.gtLayout)
        self.uncoverLayout = QtWidgets.QHBoxLayout()
        self.uncoverLayout.setContentsMargins(-1, -1, 70, -1)
        self.uncoverLayout.setObjectName("uncoverLayout")
        self.uncoverAPText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.uncoverAPText.setFont(font)
        self.uncoverAPText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uncoverAPText.setObjectName("uncoverAPText")
        self.uncoverLayout.addWidget(self.uncoverAPText)
        self.uncoverAPScore = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.uncoverAPScore.setFont(font)
        self.uncoverAPScore.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uncoverAPScore.setObjectName("uncoverAPScore")
        self.uncoverLayout.addWidget(self.uncoverAPScore)
        self.imgInfoLayout.addLayout(self.uncoverLayout)
        self.unevenLayout = QtWidgets.QHBoxLayout()
        self.unevenLayout.setContentsMargins(-1, -1, 70, -1)
        self.unevenLayout.setObjectName("unevenLayout")
        self.unevenAPText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.unevenAPText.setFont(font)
        self.unevenAPText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.unevenAPText.setObjectName("unevenAPText")
        self.unevenLayout.addWidget(self.unevenAPText)
        self.unevenAPScore = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.unevenAPScore.setFont(font)
        self.unevenAPScore.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.unevenAPScore.setObjectName("unevenAPScore")
        self.unevenLayout.addWidget(self.unevenAPScore)
        self.imgInfoLayout.addLayout(self.unevenLayout)
        self.scratchLayout = QtWidgets.QHBoxLayout()
        self.scratchLayout.setContentsMargins(-1, -1, 70, -1)
        self.scratchLayout.setObjectName("scratchLayout")
        self.scratchAPText = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.scratchAPText.setFont(font)
        self.scratchAPText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scratchAPText.setObjectName("scratchAPText")
        self.scratchLayout.addWidget(self.scratchAPText)
        self.scratchAPScore = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.scratchAPScore.setFont(font)
        self.scratchAPScore.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scratchAPScore.setObjectName("scratchAPScore")
        self.scratchLayout.addWidget(self.scratchAPScore)
        self.imgInfoLayout.addLayout(self.scratchLayout)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(390, 490, 271, 151))
        self.widget2.setObjectName("widget2")
        self.detectMetricLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.detectMetricLayout.setContentsMargins(0, 0, 0, 0)
        self.detectMetricLayout.setObjectName("detectMetricLayout")
        self.fpsLayout = QtWidgets.QHBoxLayout()
        self.fpsLayout.setContentsMargins(-1, -1, 180, -1)
        self.fpsLayout.setObjectName("fpsLayout")
        self.fpsText = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.fpsText.setFont(font)
        self.fpsText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fpsText.setObjectName("fpsText")
        self.fpsLayout.addWidget(self.fpsText)
        self.scoreOfFPS = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        self.scoreOfFPS.setFont(font)
        self.scoreOfFPS.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scoreOfFPS.setObjectName("scoreOfFPS")
        self.fpsLayout.addWidget(self.scoreOfFPS)
        self.detectMetricLayout.addLayout(self.fpsLayout)
        self.predictLayout = QtWidgets.QHBoxLayout()
        self.predictLayout.setContentsMargins(-1, -1, 0, -1)
        self.predictLayout.setObjectName("predictLayout")
        self.predictText = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.predictText.setFont(font)
        self.predictText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.predictText.setObjectName("predictText")
        self.predictLayout.addWidget(self.predictText)
        self.predictTypeText = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.predictTypeText.setFont(font)
        self.predictTypeText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.predictTypeText.setObjectName("predictTypeText")
        self.predictLayout.addWidget(self.predictTypeText)
        self.detectMetricLayout.addLayout(self.predictLayout)
        self.iouLayout = QtWidgets.QHBoxLayout()
        self.iouLayout.setContentsMargins(-1, -1, 180, -1)
        self.iouLayout.setObjectName("iouLayout")
        self.iouText = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)
        font.setUnderline(True)
        self.iouText.setFont(font)
        self.iouText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.iouText.setObjectName("iouText")
        self.iouLayout.addWidget(self.iouText)
        self.scoreOfIoU = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("IBM Plex Sans")
        font.setPointSize(18)

        self.scoreOfIoU.setFont(font)
        self.scoreOfIoU.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scoreOfIoU.setObjectName("scoreOfIoU")
        self.iouLayout.addWidget(self.scoreOfIoU)
        self.detectMetricLayout.addLayout(self.iouLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.selectFolderBtn.setText(_translate("Form", "Select Image Folder"))
        self.detectDefectsBtn.setText(_translate("Form", "Detect Defects"))
        self.segmentBtn.setText(_translate("Form", "Segment"))
        self.diceCoefficientText.setText(_translate("Form", "Dice Coefficient:"))
        self.scoreOfDC.setText(_translate("Form", "-"))
        self.originalImageText.setText(_translate("Form", "Original Image"))
        self.detectImageText_.setText(_translate("Form", "Detect Image"))
        self.segmentImageText.setText(_translate("Form", "Segment Image"))
        self.currentImageNumberText.setText(_translate("Form", "CurrentImage:"))
        self.currentImgNum.setText(_translate("Form", "-"))
        self.signOfIsolation.setText(_translate("Form", "/"))
        self.folderImageNum.setText(_translate("Form", "-"))
        self.typeText.setText(_translate("Form", "Type(Ground Truth):"))
        self.groundTruthTypeText.setText(_translate("Form", "-"))
        self.uncoverAPText.setText(_translate("Form", "AP50(uncover):"))
        self.uncoverAPScore.setText(_translate("Form", "-"))
        self.unevenAPText.setText(_translate("Form", "AP50(uneven):"))
        self.unevenAPScore.setText(_translate("Form", "-"))
        self.scratchAPText.setText(_translate("Form", "AP50(Scratch):"))
        self.scratchAPScore.setText(_translate("Form", "-"))
        self.fpsText.setText(_translate("Form", "FPS:"))
        self.scoreOfFPS.setText(_translate("Form", "-"))
        self.predictText.setText(_translate("Form", "Predict:"))
        self.predictTypeText.setText(_translate("Form", "-"))
        self.iouText.setText(_translate("Form", "IoU:"))
        self.scoreOfIoU.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
